# **Autogenerated file! Do not modify by hand!**
# Current migration: 20250121100017_add_reports.rb

Sequel.migration do
  change do
    create_enum(:genders, %w[man woman non_binary genderqueer genderfluid gender_non_conforming transgender trans_man transmasculine trans_woman transfeminine transsexual agender bigender pangender two_spirit intersex androgynous questioning unsure])
    create_enum(:orientations, %w[straight bisexual heteroflexible homoflexible gay lesbian queer pansexual omnisexual abrosexual demisexual asexual greysexual reciprosexual demiromantic aromantic greyromantic fluid fluctuating unsure questioning])
    create_enum(:languages, %w[abk aar afr aka sqi amh ara arg hye asm ava ave aym aze bam bak eus bel ben bis bos bre bul mya cat cha che nya zho chu chv cor cos cre hrv ces dan div nld dzo eng epo est ewe fao fij fin fra fry ful gla glg lug kat deu ell kal grn guj hat hau heb her hin hmo hun isl ido ibo ind ina ile iku ipk gle ita jpn jav kan kau kas kaz khm kik kin kir kom kon kor kua kur lao lat lav lim lin lit lub ltz mkd mlg msa mal mlt glv mri mar mah mon nau nav nde nbl ndo nep nor nob nno oci oji ori orm oss pli pus fas pol por pan que ron roh run rus sme smo sag san srd srp sna snd sin slk slv som sot spa sun swa ssw swe tgl tah tgk tam tat tel tha bod tir ton tso tsn tur tuk twi uig ukr urd uzb ven vie vol wln cym wol xho iii yid yor zha zul])
    create_enum(:relationship_type, %w[monogamous non_monogamous])
    create_enum(:relationship_status, %w[single partnered married])
    create_enum(:frequency, %w[never sometimes often])
    create_enum(:haves_or_have_nots, %w[have have_not])
    create_enum(:wants, %w[want_more do_not_want_more want_some do_not_want_any dont_know maybe])
    create_enum(:religions, %w[agnosticism atheism buddhism candomble catholicism christianity hinduism islam judaism rastafari sikh spiritism umbanda other])
    create_enum(:importance, %w[important not_important do_not_care])
    create_enum(:countries_iso_3166_1_alpha2, %w[ad ae af ag ai al am ao aq ar as at au aw ax az ba bb bd be bf bg bh bi bj bl bm bn bo bq br bs bt bv bw by bz ca cc cd cf cg ch ci ck cl cm cn co cr cu cv cw cx cy cz de dj dk dm do dz ec ee eg eh er es et fi fj fk fm fo fr ga gb gd ge gf gg gh gi gl gm gn gp gq gr gs gt gu gw gy hk hm hn hr ht hu id ie il im in io iq ir is it je jm jo jp ke kg kh ki km kn kp kr kw ky kz la lb lc li lk lr ls lt lu lv ly ma mc md me mf mg mh mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nc ne nf ng ni nl no np nr nu nz om pa pe pf pg ph pk pl pm pn pr ps pt pw py qa re ro rs ru rw sa sb sc sd se sg sh si sj sk sl sm sn so sr ss st sv sx sy sz tc td tf tg th tj tk tl tm tn to tr tt tv tw tz ua ug um us uy uz va vc ve vg vi vn vu wf ws ye yt za zm zw])
    create_enum(:sender_values, %w[profile1 profile2])
    create_enum(:report_type, %w[spam intimidation harassment minors against_rules illegal other])

    create_table(:account_statuses) do
      column :id, "integer", null: false
      column :name, "text", null: false

      primary_key %i[id]

      index %i[name], name: :account_statuses_name_key, unique: true
    end

    create_table(:locations) do
      primary_key :id, type: :Bignum
      column :geom, "geometry(Point,4326)", null: false
      column :display_name, "jsonb", null: false
      column :osm_id, "bigint", null: false
      column :country_code, "countries_iso_3166_1_alpha2", null: false

      index %i[geom]
      index %i[osm_id], name: :locations_osm_id_key, unique: true
    end

    create_table(:schema_info_password) do
      column :filename, "text", null: false

      primary_key %i[filename]
    end

    create_table(:schema_migrations) do
      column :filename, "text", null: false

      primary_key %i[filename]
    end

    create_table(:spatial_ref_sys) do
      column :srid, "integer", null: false
      column :auth_name, "character varying(256)"
      column :auth_srid, "integer"
      column :srtext, "character varying(2048)"
      column :proj4text, "character varying(2048)"

      primary_key %i[srid]
    end

    create_table(:accounts) do
      primary_key :id, type: :Bignum
      foreign_key :status_id, :account_statuses, default: 1, null: false, key: %i[id]
      column :email, "citext", null: false
    end

    create_table(:account_active_session_keys) do
      foreign_key :account_id, :accounts, type: "bigint", null: false, key: %i[id]
      column :session_id, "text", null: false
      column :created_at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :last_use, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[account_id session_id]
    end

    create_table(:account_activity_times) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :last_activity_at, "timestamp without time zone", null: false
      column :last_login_at, "timestamp without time zone", null: false
      column :expired_at, "timestamp without time zone"

      primary_key %i[id]
    end

    create_table(:account_authentication_audit_logs) do
      primary_key :id, type: :Bignum
      foreign_key :account_id, :accounts, type: "bigint", null: false, key: %i[id]
      column :at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :message, "text", null: false
      column :metadata, "jsonb"

      index %i[account_id at], name: :audit_account_at_idx
      index %i[at], name: :audit_at_idx
    end

    create_table(:account_email_auth_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :email_last_sent, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_jwt_refresh_keys) do
      primary_key :id, type: :Bignum
      foreign_key :account_id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      index %i[account_id], name: :account_jwt_rk_account_id_idx
    end

    create_table(:account_lockouts) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :email_last_sent, "timestamp without time zone"

      primary_key %i[id]
    end

    create_table(:account_login_change_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :login, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_login_failures) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :number, "integer", default: 1, null: false

      primary_key %i[id]
    end

    create_table(:account_otp_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :num_failures, "integer", default: 0, null: false
      column :last_use, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_password_change_times) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :changed_at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_password_hashes) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :password_hash, "text", null: false

      primary_key %i[id]
    end

    create_table(:account_password_reset_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :email_last_sent, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_previous_password_hashes) do
      primary_key :id, type: :Bignum
      foreign_key :account_id, :accounts, type: "bigint", key: %i[id]
      column :password_hash, "text", null: false
    end

    create_table(:account_recovery_codes) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :code, "text", null: false

      primary_key %i[id code]
    end

    create_table(:account_remember_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :deadline, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_session_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false

      primary_key %i[id]
    end

    create_table(:account_sms_codes) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :phone_number, "text", null: false
      column :num_failures, "integer"
      column :code, "text"
      column :code_issued_at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_verification_keys) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :key, "text", null: false
      column :requested_at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :email_last_sent, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[id]
    end

    create_table(:account_webauthn_keys) do
      foreign_key :account_id, :accounts, type: "bigint", null: false, key: %i[id]
      column :webauthn_id, "text", null: false
      column :public_key, "text", null: false
      column :sign_count, "integer", null: false
      column :last_use, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false

      primary_key %i[account_id webauthn_id]
    end

    create_table(:account_webauthn_user_ids) do
      foreign_key :id, :accounts, type: "bigint", null: false, key: %i[id]
      column :webauthn_id, "text", null: false

      primary_key %i[id]
    end

    create_table(:profiles) do
      foreign_key :account_id, :accounts, type: "bigint", null: false, key: %i[id]
      column :created_at, "timestamp without time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :display_name, "text", null: false
      column :about_me, "text"
      column :birth_date, "date"
      column :genders, "genders[]"
      column :orientations, "orientations[]"
      column :languages, "languages[]"
      column :relationship_type, "relationship_type"
      column :relationship_status, "relationship_status"
      column :tobacco, "frequency"
      column :marijuana, "frequency"
      column :alcohol, "frequency"
      column :other_recreational_drugs, "frequency"
      column :pets, "haves_or_have_nots"
      column :wants_pets, "wants"
      column :kids, "haves_or_have_nots"
      column :wants_kids, "wants"
      column :religion, "religions"
      column :religion_importance, "importance"
      foreign_key :location_id, :locations, type: "bigint", key: %i[id]
      column :id, "uuid", default: Sequel::LiteralString.new("uuid_generate_v7()"), null: false
      column :picture, "jsonb"
      column :hide_age, "boolean", default: false, null: false

      primary_key %i[id]
    end

    create_table(:conversations) do
      column :id, "uuid", default: Sequel::LiteralString.new("uuid_generate_v7()"), null: false
      foreign_key :profile1_id, :profiles, type: "uuid", null: false, key: %i[id]
      foreign_key :profile2_id, :profiles, type: "uuid", null: false, key: %i[id]
      column :created_at, "timestamp with time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :profile1_last_seen_at, "timestamp with time zone"
      column :profile2_last_seen_at, "timestamp with time zone"

      primary_key %i[id]

      index %i[profile1_id profile2_id], unique: true
    end

    create_table(:profile_blocks) do
      primary_key :id, type: :Bignum
      column :created_at, "timestamp with time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      foreign_key :profile_id, :profiles, type: "uuid", null: false, key: %i[id]
      foreign_key :target_profile_id, :profiles, type: "uuid", null: false, key: %i[id]

      index %i[profile_id target_profile_id], unique: true
    end

    create_table(:reports) do
      primary_key :id, type: :Bignum
      column :created_at, "timestamp with time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :updated_at, "timestamp with time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :message_ids, "bigint[]", default: Sequel::LiteralString.new("ARRAY[]::bigint[]")
      column :comment, "text"
      column :type, "report_type", null: false
      foreign_key :profile_id, :profiles, type: "uuid", null: false, key: %i[id]
      foreign_key :target_profile_id, :profiles, type: "uuid", null: false, key: %i[id]
    end

    create_table(:messages) do
      primary_key :id, type: :Bignum
      foreign_key :conversation_id, :conversations, type: "uuid", null: false, key: %i[id]
      column :sender, "sender_values", null: false
      column :sent_at, "timestamp with time zone", default: Sequel::CURRENT_TIMESTAMP, null: false
      column :content, "text", null: false
    end
  end
end
